version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "store-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kktab8o7vkjk"
s3_prefix = "store-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
